# Generated by Django 5.2.15 on 2026-06-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(default='Technical', max_length=100)),
                ('proficiency', models.IntegerField(default=80, help_text='Proficiency percentage from 1 to 100')),
            ],
        ),
    ]
