# Generated by Django 5.2.15 on 2026-06-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('item_type', models.CharField(choices=[('project', 'Personal Project'), ('experience', 'Professional Experience'), ('academic', 'Academic Project')], default='project', max_length=20)),
                ('description', models.TextField()),
                ('technologies', models.CharField(help_text='Comma-separated technologies used', max_length=200)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.CharField(blank=True, help_text='Link to github repo or demo', max_length=255, null=True)),
            ],
        ),
    ]
